default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: teisyutukadai_development

test:
  <<: *default
  database: teisyutukadai_test

production:
  <<: *default
  database: teisyutukadai_production
  username: teisyutukadai
  password: <%= ENV['TEISYUTUKADAI_DATABASE_PASSWORD'] %>
